"""Recommendations router - Connected to Decision Engine outputs."""

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from sqlalchemy import text
from typing import Optional
import logging

from api.database import get_db
from api.schemas.recommendation import Recommendation, RecommendationListResponse
from api.schemas.common import PaginationParams, ErrorResponse
from src.decision_intelligence.decision_engine import DecisionEngine
from src.data_platform.data_loader import DataLoader
from datetime import date
from api.auth.dependencies import require_permission
from api.auth.models import Permission

logger = logging.getLogger(__name__)

router = APIRouter()


@router.get("/recommendations", response_model=RecommendationListResponse)
async def get_recommendations(
    pagination: PaginationParams = Depends(),
    segment: Optional[str] = Query(None, description="Filter by segment"),
    priority: Optional[str] = Query(None, description="Filter by priority"),
    customer_key: Optional[str] = Query(None, description="Filter by customer key"),
    db: Session = Depends(get_db),
    current_user = Depends(require_permission(Permission.ANALYTICS_READ))
):
    """Get list of recommendations with pagination and filters.
    
    This endpoint returns recommendations generated by the Decision Engine.
    
    Args:
        pagination: Pagination parameters
        segment: Optional segment filter
        priority: Optional priority filter
        customer_key: Optional customer key filter
        db: Database session
    
    Returns:
        RecommendationListResponse: List of recommendations
    """
    try:
        # Build query
        query = "SELECT * FROM fact_recommendations WHERE 1=1"
        params = {}
        
        if segment:
            query += " AND segment = :segment"
            params["segment"] = segment
        
        if priority:
            query += " AND priority = :priority"
            params["priority"] = priority
        
        if customer_key:
            query += " AND customer_key = :customer_key"
            params["customer_key"] = customer_key
        
        # Get total count
        count_query = query.replace("SELECT *", "SELECT COUNT(*)")
        total = db.execute(text(count_query), params).scalar()
        
        # Get paginated results
        query += f" ORDER BY generated_at DESC, priority DESC LIMIT :limit OFFSET :offset"
        params["limit"] = pagination.page_size
        params["offset"] = pagination.offset
        
        result = db.execute(text(query), params).fetchall()
        
        recommendations = [Recommendation(**row._asdict()) for row in result]
        
        return RecommendationListResponse(
            recommendations=recommendations,
            total=total
        )
    except Exception as e:
        logger.error(f"Error fetching recommendations: {e}")
        raise HTTPException(status_code=500, detail="Error fetching recommendations")


@router.post("/recommendations/generate")
async def generate_recommendations(
    customer_keys: Optional[list[str]] = None,
    db: Session = Depends(get_db),
    current_user = Depends(require_permission(Permission.ANALYTICS_EXECUTE))
):
    """Generate new recommendations using the Decision Engine.
    
    This endpoint triggers the Decision Engine to generate recommendations
    based on the latest ML predictions and business rules.
    
    Args:
        customer_keys: Optional list of customer keys to generate recommendations for
        db: Database session
    
    Returns:
        Dictionary with generation results
    """
    try:
        # Initialize decision engine
        data_loader = DataLoader()
        decision_engine = DecisionEngine(data_loader=data_loader)
        
        # Generate recommendations
        recommendations_df = decision_engine.generate_customer_recommendations(
            customer_keys=customer_keys
        )
        
        if recommendations_df.empty:
            return {
                "status": "success",
                "message": "No recommendations generated",
                "count": 0
            }
        
        # Persist recommendations to database
        # This would use SQLAlchemy to insert into fact_recommendations
        # For now, just return the count
        
        return {
            "status": "success",
            "message": f"Generated {len(recommendations_df)} recommendations",
            "count": len(recommendations_df),
            "recommendations": recommendations_df.to_dict('records')
        }
    except Exception as e:
        logger.error(f"Error generating recommendations: {e}")
        raise HTTPException(status_code=500, detail="Error generating recommendations")


@router.get("/recommendations/summary")
async def get_recommendation_summary(
    as_of_date: Optional[date] = None,
    db: Session = Depends(get_db),
    current_user = Depends(require_permission(Permission.ANALYTICS_READ))
):
    """Get summary of recommendations.
    
    Args:
        as_of_date: Optional as-of date for summary
        db: Database session
    
    Returns:
        Dictionary with recommendation summary
    """
    try:
        # Initialize decision engine
        data_loader = DataLoader()
        decision_engine = DecisionEngine(data_loader=data_loader, as_of_date=as_of_date)
        
        # Get summary
        summary = decision_engine.get_recommendation_summary()
        
        return summary
    except Exception as e:
        logger.error(f"Error fetching recommendation summary: {e}")
        raise HTTPException(status_code=500, detail="Error fetching recommendation summary")


@router.get("/recommendations/segment/{segment}")
async def get_segment_recommendations(
    segment: str,
    db: Session = Depends(get_db),
    current_user = Depends(require_permission(Permission.ANALYTICS_READ))
):
    """Get recommendations for a specific segment.
    
    Args:
        segment: Segment name
        db: Database session
    
    Returns:
        Segment recommendations
    """
    try:
        # Initialize decision engine
        data_loader = DataLoader()
        decision_engine = DecisionEngine(data_loader=data_loader)
        
        # Generate segment recommendations
        segment_recommendations = decision_engine.generate_segment_recommendations()
        
        if segment not in segment_recommendations:
            raise HTTPException(status_code=404, detail=f"Segment {segment} not found")
        
        return {
            "segment": segment,
            "recommendations": [rec.to_dict() for rec in segment_recommendations[segment]]
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error fetching segment recommendations: {e}")
        raise HTTPException(status_code=500, detail="Error fetching segment recommendations")
