"""SQLAlchemy models for banking analytics warehouse."""

from src.models.base import Base
from src.models.dimensions import (
    DimCustomer,
    DimAccount,
    DimProduct,
    DimBranch,
    DimDate,
    DimCustomerSegment,
)
from src.models.facts import (
    FactTransaction,
    FactLoan,
    FactLoanPayment,
    FactCardTransaction,
    FactCustomerInteraction,
    FactCustomerProfitability,
    FactCustomerRisk,
)
from src.models.streaming import (
    FactRealtimeEvent,
    FactEventProcessingLog,
    FactStreamingPrediction,
    FactStreamingAnomaly,
    FactRiskEvent,
    FactAlert,
    FactDecisionAudit,
    DimModelRegistry,
    FactReconciliationResult,
    FactReplayRun,
    EventStatus,
    ProcessingStatus,
    Severity,
    AlertStatus,
    ModelValidationStatus,
    ModelDeploymentStatus,
    ReconciliationStatus,
    ReplayStatus,
)

__all__ = [
    "Base",
    "DimCustomer",
    "DimAccount",
    "DimProduct",
    "DimBranch",
    "DimDate",
    "DimCustomerSegment",
    "FactTransaction",
    "FactLoan",
    "FactLoanPayment",
    "FactCardTransaction",
    "FactCustomerInteraction",
    "FactCustomerProfitability",
    "FactCustomerRisk",
    "FactRealtimeEvent",
    "FactEventProcessingLog",
    "FactStreamingPrediction",
    "FactStreamingAnomaly",
    "FactRiskEvent",
    "FactAlert",
    "FactDecisionAudit",
    "DimModelRegistry",
    "FactReconciliationResult",
    "FactReplayRun",
    "EventStatus",
    "ProcessingStatus",
    "Severity",
    "AlertStatus",
    "ModelValidationStatus",
    "ModelDeploymentStatus",
    "ReconciliationStatus",
    "ReplayStatus",
]
